service: alert-notification-hy

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 1024
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2

functions: 
  get-generated-dog-name:
    handler: src/handlers/get-generated-dog-name/endpoint.handler
    events: 
      - http: 
          path: generate/{breed}/name
          method: get
          cors: true
  slack-notifications:
    handler: src/handlers/slack-notification/slack-notification.handler
    environment:
      SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
    events:
      - sns:
          arn:
            Ref: InvalidNameNotificationHY
          topicName: Invalid-Name-Notification-hy

resources: # CloudFormation template syntax
  Resources:
    InvalidNameNotificationHY:
      Type: AWS::SNS::Topic
      Properties: 
        TopicName: Invalid-Name-Notification-hy

    InvalidNameAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: hy-InvalidNameAlarm
        AlarmDescription: Get generated dog name lambda alarm
        Namespace: AWS/ApiGateway
        MetricName: 5XXError
        Dimensions:
          - Name: ApiName
            Value: ${self:provider.stage}-${self:service}
        Statistic: Sum
        ComparisonOperator: GreaterThanThreshold
        Threshold: 0
        Period: 60
        EvaluationPeriods: 1
        AlarmActions:
          - Ref: InvalidNameNotificationHY

    