agents:
  queue: '210630331612:cicd'
steps:
  - label: ':rocket: Deploy Serverless'
    commands:
      - yarn
      - serverless deploy
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SLACK_WEBHOOK_URL: ProjectMarioSlackWebhook
      - docker#v3.8.0:
          image: node:16
          environment:
            - SLACK_WEBHOOK_URL
